[phases.setup]
cmds = [
    "apt-get update",
    "apt-get install -y ffmpeg python3.11 python3.11-dev"
]

[phases.install]
cmds = [
    "python3.11 -m pip install -r requirements.txt"
]

[start]
cmd = "python3.11 -m uvicorn app:app --host 0.0.0.0 --port $PORT"