[phases.setup]
cmds = [
    "apt-get update",
    "apt-get install -y ffmpeg"
]

[phases.install]
cmds = [
    "pip install -r requirements.txt"
]

[start]
cmd = "python -m uvicorn app:app --host 0.0.0.0 --port $PORT"